/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ali' at '12/6/16 6:07 PM' with Gradle 2.14.1
 *
 * @author Ali, @date 12/6/16 6:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
